version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - csstree
  - Flexbox
  - oklab
  - oklch
  - prophoto
  - stringifiers
  - turbopack
  - unittests
ignoreWords: []
import: []
