version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cornflowerblue
  - csstree
  - currentcolor
  - Flexbox
  - oklab
  - oklch
  - prophoto
  - rebeccapurple
  - reparsed
  - rgba
  - rotatex
  - rotatey
  - rotatez
  - RRGGBB
  - RRGGBBAA
  - scalex
  - scaley
  - scalez
  - srgb
  - stringifiers
  - translatex
  - translatey
  - translatez
  - turbopack
  - unittests
  - vmax
  - vmin
ignoreWords: []
import: []
