version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - clippath
  - cornflowerblue
  - csstree
  - currentcolor
  - evenodd
  - Flexbox
  - grayscale
  - justfile
  - longhands
  - mynew
  - notacolor
  - notvalid
  - oklab
  - oklch
  - oneline
  - parseable
  - prophoto
  - rebeccapurple
  - reparsed
  - rgba
  - roadmaps
  - rotatex
  - rotatey
  - rotatez
  - RRGGBB
  - RRGGBBAA
  - scalex
  - scaley
  - scalez
  - srgb
  - stringifiers
  - translatex
  - translatey
  - translatez
  - trbl
  - TRBL
  - turbopack
  - unitless
  - unittests
  - vmax
  - vmin
  - xywh
  - zindex
ignoreWords: []
import: []
